# app.py - VARIA Carbon Predictor
# Direct model loading version - No API dependency

import streamlit as st
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
import joblib
import numpy as np
from io import BytesIO
import base64

# Page configuration
st.set_page_config(page_title="VARIA Carbon Predictor - AI Soil Intelligence", layout="wide", page_icon="🌾")

# Load model directly (cached for performance)
@st.cache_resource
def load_model():
    return joblib.load('carbon_model_real_70.pkl')

# Function to create sample PDF (simulated download)
def get_sample_pdf_download():
    # Create a simple HTML report that can be downloaded as PDF
    sample_html = """
    <html>
    <head><style>
        body { font-family: Arial; padding: 40px; }
        h1 { color: #1a5d3a; }
        .result { background: #f0fdf4; padding: 20px; border-radius: 10px; }
        .metric { font-size: 24px; font-weight: bold; color: #1a5d3a; }
    </style></head>
    <body>
        <h1>🌾 VARIA Carbon Report (Sample)</h1>
        <p><strong>Farm ID:</strong> SAMPLE-FARM-001</p>
        <p><strong>Date:</strong> March 2026</p>
        <div class="result">
            <h2>Soil Organic Carbon: <span class="metric">5.8%</span></h2>
            <p>✅ Moderate to High Carbon Level</p>
            <h3>Recommendations:</h3>
            <ul>
                <li>Maintain cover cropping</li>
                <li>Reduce tillage frequency</li>
                <li>Potential carbon credits: ~2.9 tons CO₂/ha/year</li>
            </ul>
        </div>
        <p style="margin-top: 40px; color: #666;">Generated by VARIA AgTech Studio</p>
    </body>
    </html>
    """
    b64 = base64.b64encode(sample_html.encode()).decode()
    href = f'<a href="data:text/html;base64,{b64}" download="VARIA_Sample_Report.html">📥 Download Sample Report (HTML)</a>'
    return href

# Custom CSS for better styling
st.markdown("""
<style>
    .stApp {
        background: linear-gradient(135deg, #f8fafc 0%, #e8f5e9 100%);
    }
    .stButton button {
        background-color: #1a5d3a;
        color: white;
        border-radius: 30px;
        padding: 10px 30px;
        font-weight: bold;
        transition: all 0.3s ease;
    }
    .stButton button:hover {
        background-color: #2d6a4f;
        transform: scale(1.02);
    }
    .info-box {
        background: linear-gradient(135deg, #1a5d3a10 0%, #2d6a4f10 100%);
        padding: 20px;
        border-radius: 15px;
        border-left: 4px solid #1a5d3a;
        margin-bottom: 20px;
    }
    .cta-box {
        background: linear-gradient(135deg, #1a5d3a 0%, #2d6a4f 100%);
        padding: 20px;
        border-radius: 15px;
        color: white;
        text-align: center;
    }
    .css-1kyxreq {
        background: rgba(26, 93, 58, 0.05);
    }
    hr {
        margin: 20px 0;
    }
</style>
""", unsafe_allow_html=True)

# ========== HEADER SECTION ==========
col1, col2, col3 = st.columns([1, 2, 1])
with col2:
    st.title("🌾 VARIA Carbon Predictor")
    st.markdown("<p style='text-align: center; color: #1a5d3a; font-size: 18px;'>🤖 AI-Powered Soil Organic Carbon Estimation</p>", unsafe_allow_html=True)

# ========== VALUE PROPOSITION BOX ==========
st.markdown("""
<div class="info-box">
    <h3>🎯 What is this tool?</h3>
    <p><strong>For farmers, agronomists, and carbon project developers:</strong><br>
    Estimate your soil's organic carbon using 5 simple inputs. No field sampling. No lab costs. Results in seconds.</p>
    <p>✅ <strong>Use cases:</strong> Carbon credit assessment | Soil health monitoring | Regenerative agriculture planning</p>
</div>
""", unsafe_allow_html=True)

st.markdown("---")

# ========== INPUT SECTION ==========
st.subheader("📊 Enter Your Soil & Climate Data")

with st.form("carbon_form"):
    col1, col2 = st.columns(2)
    
    with col1:
        ndvi = st.number_input(
            "🌿 NDVI (Vegetation Index)", 
            min_value=0.0, max_value=1.0, 
            value=0.6, step=0.01,
            help="Normalized Difference Vegetation Index (0.1 = barren, 0.8 = dense forest)"
        )
        precipitation = st.number_input(
            "💧 Annual Precipitation (mm/year)", 
            min_value=0, value=600, step=50,
            help="mm per year"
        )
        temperature = st.number_input(
            "🌡️ Mean Annual Temperature (°C)", 
            min_value=-10, value=17, step=1,
            help="°Celsius"
        )
    
    with col2:
        elevation = st.number_input(
            "⛰️ Elevation (meters)", 
            min_value=0, value=300, step=50,
            help="meters above sea level"
        )
        clay = st.number_input(
            "🪨 Clay Content (%)", 
            min_value=0, max_value=100, value=25, step=5,
            help="percentage of clay in soil"
        )
    
    # Sample report download link outside form
    st.markdown("---")
    st.markdown("### 📄 Want to see what you'll get?")
    st.markdown(get_sample_pdf_download(), unsafe_allow_html=True)
    st.markdown("*No data entry needed — see a sample report instantly*")
    
    submitted = st.form_submit_button("🔍 Predict Soil Carbon", use_container_width=True)

# ========== MODEL LOADING ==========
try:
    model = load_model()
    model_loaded = True
except Exception as e:
    model_loaded = False
    st.error(f"⚠️ Model loading error: {e}. Please check if 'carbon_model_real_70.pkl' exists.")

# ========== RESULTS SECTION ==========
if submitted and model_loaded:
    input_array = np.array([[ndvi, precipitation, temperature, elevation, clay]])
    
    try:
        prediction = model.predict(input_array)[0]
        carbon = round(prediction, 2)
        
        # Display main result
        col1, col2, col3 = st.columns([1, 2, 1])
        with col2:
            st.markdown("---")
            st.markdown("<h2 style='text-align: center;'>📊 Your Soil Carbon Result</h2>", unsafe_allow_html=True)
            
            # Gauge Chart
            fig = go.Figure(go.Indicator(
                mode="gauge+number+delta",
                value=carbon,
                title={'text': "Soil Organic Carbon (%)", 'font': {'size': 16}},
                domain={'x': [0, 1], 'y': [0, 1]},
                gauge={
                    'axis': {'range': [0, 10], 'tickwidth': 1},
                    'bar': {'color': "#1a5d3a"},
                    'steps': [
                        {'range': [0, 2], 'color': "#ef4444"},
                        {'range': [2, 4], 'color': "#f59e0b"},
                        {'range': [4, 6], 'color': "#eab308"},
                        {'range': [6, 8], 'color': "#84cc16"},
                        {'range': [8, 10], 'color': "#22c55e"}
                    ],
                    'threshold': {
                        'line': {'color': "red", 'width': 4},
                        'thickness': 0.75,
                        'value': carbon
                    }
                }
            ))
            fig.update_layout(height=300, margin=dict(l=20, r=20, t=40, b=20))
            st.plotly_chart(fig, use_container_width=True)
            
            # Advice based on carbon level
            if carbon > 6:
                st.success(f"🌱 **{carbon}% - Carbon-rich soil!** ✅ Good potential for carbon credits.")
                st.markdown("> 💡 **Next step:** [Contact us](mailto:mah.kzmi21@gmail.com) for carbon credit verification")
            elif carbon > 3:
                st.warning(f"⚠️ **{carbon}% - Moderate soil carbon.** You can increase it with proper management.")
                st.markdown("> 📘 **Tip:** Conservation tillage + cover crops can boost this by 15-25%")
            else:
                st.error(f"❌ **{carbon}% - Low soil carbon.** Action needed to improve soil fertility.")
                st.markdown("> 🌿 **Recommendation:** Start with compost application and reduced tillage")
        
        # Feature Importance Chart
        st.markdown("---")
        st.subheader("📈 Parameter Impact Analysis")
        
        impact_data = pd.DataFrame({
            'Parameter': ['NDVI', 'Precipitation', 'Temperature', 'Elevation', 'Clay'],
            'Impact (%)': [
                round(ndvi * 100, 1),
                round(precipitation / 1300 * 100, 1),
                round(max(0, (30 - temperature) / 30 * 100), 1),
                round(max(0, (2500 - elevation) / 2500 * 100), 1),
                round(clay / 60 * 100, 1)
            ]
        })
        
        fig2 = px.bar(impact_data, x='Parameter', y='Impact (%)', 
                     color='Impact (%)', color_continuous_scale='Greens',
                     title="Relative Impact of Each Parameter on Soil Carbon")
        fig2.update_layout(height=400, showlegend=False)
        st.plotly_chart(fig2, use_container_width=True)
        
        # Carbon Credit Potential
        st.markdown("---")
        st.subheader("💰 Carbon Credit Potential")
        if carbon > 4:
            est_credits = round(carbon * 0.5, 1)
            st.info(f"🌍 Estimated carbon credits per hectare: **{est_credits} tons CO₂ equivalent/year**")
            st.markdown("📧 **Interested in monetizing this?** [Get in touch](mailto:mah.kzmi21@gmail.com) for verification and market access.")
        else:
            st.warning("⚠️ Carbon level below 4% — threshold for credit generation typically starts at 4-5%")
            st.markdown("💪 **Focus on soil building first.** We can help with a custom plan.")
        
        # ========== EMAIL COLLECTION (NEW) ==========
        st.markdown("---")
        st.markdown("### 📬 Want a detailed report?")
        
        with st.form("email_collection"):
            st.markdown("Get a **full PDF report** with personalized recommendations sent to your inbox. No spam. Just one report.")
            email = st.text_input("Your email address", placeholder="farmer@example.com")
            submit_email = st.form_submit_button("📧 Send Me Full Report")
            
            if submit_email and email:
                if "@" in email and "." in email:
                    st.success(f"✅ Thanks! We'll send the full report to {email} within 24 hours.")
                    # You can later connect this to Google Sheets or Email API
                    st.balloons()
                elif submit_email:
                    st.error("Please enter a valid email address")
        
    except Exception as e:
        st.error(f"❌ Prediction error: {e}")
        
elif submitted and not model_loaded:
    st.error("❌ Model not loaded. Please check the model file.")

# ========== FOOTER ==========
st.markdown("---")
st.markdown("""
<div style="text-align: center; color: #888; font-size: 12px;">
    <p>© 2026 VARIA AgTech Studio — Soil Intelligence for a Regenerative Future</p>
    <p>📧 mah.kzmi21@gmail.com | mahdieh.kazemi.m@ut.ac.ir</p>
    <p>🌐 <a href="https://www.producthunt.com/products/varia-carbon-predictor" target="_blank">View on Product Hunt</a></p>
</div>
""", unsafe_allow_html=True)